### PR TITLE
Update janet and judge to latest versions

### PR DESCRIPTION
**Pull request by jpaquim**
Remove walkies functions due to Janet integrating equivalent changes upstream: https://github.com/janet-lang/janet/pull/1095/files

Updates Janet to the latest commit (fc8c6a429eafacb88097aaf3ec7de17871a14013), and the Judge test to reflect the latest version's changes to the spec macros

### CODE REVIEW

**Comment by ianthehenry** [comment]
Hey thanks! Can we make it be the stable Janet-1.28.0 release instead of the current HEAD? While I doubt there are any breaking changes there is an annoying (and undocumented) dependency where the Janet that you use to build Bauble has to be the same as the version that Bauble vendors here or crazy things could happen.

Also! The `janet.c.patch` thing is totally unnecessary now! The root bug was fixed in a previous release and we can just delete that now.

**Comment by jpaquim** [comment]
Hey @ianthehenry! I just updated the branch to use the stable version of Janet instead and remove the patch.

Also, given that the patch is unnecessary, does it still make sense to explicitly vendor a copy of janet rather than download it as part of a build script or keep it as a git submodule? I see upsides to either approach, just wondering what you think about this

**Comment by ianthehenry** [comment]
Looks great! And yeah, I think that downloading it as a build step would make sense. The explicit vendoring was mostly just easy/lazy because Bauble didn't have any kind of build system when I started it :).

I don't think we can do it as a submodule because the amalgamated build isn't part of the janet repo? So it would require first building the amalgamted c file as a build step in here and I think that's probably harder than it's worth?

**Comment by ianthehenry** [comment]
My extremely high-tech Bauble dev tools:

```
nix-shell ~/src/bauble ➜ sd bauble update-janet --cat
#!/usr/bin/env bash

set -euo pipefail

cd ~/src/bauble

version="v$1"

curl -L "https://github.com/janet-lang/janet/releases/download/${version}/janet.c" > janet/janet.c
curl -L "https://github.com/janet-lang/janet/releases/download/${version}/janet.h" > janet/janet.h
```

:p

**Comment by ianthehenry** [comment]
Actually yeah I'm just gonna do this now

**Comment by ianthehenry** [comment]
done in 5dae2e1460a1c4ea3bf2f58947b35d6f3ee0e852

**Pull request merged**
